name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [25]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Build
        run: mvn -B package

  publish:
    name: Publish to Maven Central

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Central Portal
        run: mvn -B -Pdeploy,release deploy -DskipTests
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
